/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated session user */
        get: operations["AuthController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recipes owned by the authenticated user */
        get: operations["RecipesController_findMine"];
        put?: never;
        /** Create a recipe owned by the authenticated user */
        post: operations["RecipesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List public recipes */
        get: operations["RecipesController_findPublic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a recipe by id when visible to the requester */
        get: operations["RecipesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a recipe owned by the authenticated user */
        patch: operations["RecipesController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SessionUserDto: {
            /** @example user_123 */
            id: string;
            /** @example Ada Lovelace */
            name: string | null;
            /** @example ada@example.com */
            email: string | null;
            /** @example https://lh3.googleusercontent.com/a/example */
            image: string | null;
        };
        MeResponseDto: {
            user: components["schemas"]["SessionUserDto"];
        };
        CreateRecipeDto: {
            /**
             * @description Recipe title.
             * @example Pasta al pomodoro
             */
            title: string;
            /**
             * @description Optional recipe description.
             * @example Simple tomato pasta for weeknights.
             */
            description?: string | null;
            /**
             * @description Recipe visibility status. Defaults to DRAFT.
             * @default DRAFT
             * @enum {string}
             */
            status: "DRAFT" | "PRIVATE" | "PUBLIC";
        };
        RecipeResponseDto: {
            /** @example recipe_123 */
            id: string;
            /** @example Pasta al pomodoro */
            title: string;
            /** @example Simple tomato pasta for weeknights. */
            description: string | null;
            /**
             * @example DRAFT
             * @enum {string}
             */
            status: "DRAFT" | "PRIVATE" | "PUBLIC";
            /**
             * Format: date-time
             * @example 2026-06-27T10:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-06-27T10:00:00.000Z
             */
            updatedAt: string;
        };
        RecipeListItemDto: {
            /** @example recipe_123 */
            id: string;
            /** @example Pasta al pomodoro */
            title: string;
            /** @example Simple tomato pasta for weeknights. */
            description: string | null;
            /**
             * @example DRAFT
             * @enum {string}
             */
            status: "DRAFT" | "PRIVATE" | "PUBLIC";
            /**
             * Format: date-time
             * @example 2026-06-27T10:00:00.000Z
             */
            createdAt: string;
        };
        UpdateRecipeDto: {
            /**
             * @description Recipe title. When present, it cannot be empty.
             * @example Updated pasta
             */
            title?: string;
            /**
             * @description Recipe description. Send null to clear it.
             * @example Updated recipe notes.
             */
            description?: string | null;
            /**
             * @description Recipe visibility status.
             * @enum {string}
             */
            status?: "DRAFT" | "PRIVATE" | "PUBLIC";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
            /** @description No valid session cookie was sent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecipesController_findMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeListItemDto"][];
                };
            };
            /** @description No valid session cookie was sent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecipesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecipeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponseDto"];
                };
            };
            /** @description Request body failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid session cookie was sent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecipesController_findPublic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeListItemDto"][];
                };
            };
        };
    };
    RecipesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponseDto"];
                };
            };
            /** @description Recipe not found or not visible. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecipesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecipeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponseDto"];
                };
            };
            /** @description Request body failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid session cookie was sent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Recipe not found for this owner. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
